package ascripts

import (
	"github.com/jpfluger/alibs-slim/ajson"
)

// IScriptable defines the interface for scriptable objects.
type IScriptable interface {
	// GetKey retrieves the unique identifier for the scriptable object.
	GetKey() ajson.JsonKey

	// GetType retrieves the type of the scriptable object.
	GetType() ScriptType
	// SetType sets the type of the scriptable object.
	SetType(scriptType ScriptType)

	// GetBody retrieves the body content of the scriptable object.
	GetBody() string

	// CanCompile checks if the scriptable object has the necessary properties to be compiled.
	CanCompile() bool

	// Compile compiles the scriptable object with the given parameters and returns the result or an error.
	// The calling function is responsible for interpreting the returned object.
	// The required parameters may vary depending on the compiler used.
	Compile(params interface{}) (returnedItem interface{}, err error)

	// Render processes the scriptable object with the given data and returns the result as a string or an error.
	// The underlying implementation is expected to return a string, whether it is generated by a compiler or not.
	// Render is intended for generating non-cached return values.
	Render(data interface{}) (string, error)

	// RenderWithCache processes the scriptable object with the given data and returns the result as a string.
	// It uses a cached value if available and the refreshCache flag is not set.
	// If refreshCache is true, the cache is refreshed with the new result.
	RenderWithCache(data interface{}, refreshCache bool) (string, error)
}
